# -*- coding: utf-8 -*-
"""Tensors_demo_day11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zi-Y1XpXQ-MitcMSjH3CtKltevut9Zx8
"""

import numpy as np

a= np.array(4)

a# this is a scaller or 0D tensor

a.ndim #dimention  of the array

#1d tensor
arr=np.array([1,2,34,5,6])
arr
arr.ndim

#2d Tensors
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

mat.ndim