# -*- coding: utf-8 -*-
"""working_with_json.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WSvjnFjYIs2HYt7sUnrbsqs3WEbjiJIp
"""

import pandas as pd

pd.read_json('train.json')

#to work with  sql we have to install library
!pip install mysql.connector

import mysql.connector

conn=mysql.connector.connect(host='localhost', user='root', password='', database='world')

pd.read_sql_query("SELECT * FROM city", conn)