# -*- coding: utf-8 -*-
"""youtube_data_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YW1RqZqYUP38T7esMS9_NVMw8Q4GdybQ
"""

!pip install google-api-python-client

from apiclient.discovery import build

api_key="AIzaSyCCMX4AV3obbGj90j9QYLznP3RiglyZ-YU"

youtube = build('youtube', 'v3', developerKey=api_key)

type(youtube)

#search api to search on youtube

req = youtube.search().list(q='marvel', part='snippet', type='video', maxResults=5)

res= req.execute()

res

res['items']

len(res['items'])

for item in res['items']:
  print(item['snippet']['title'])